server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: chanho
    password: chanho

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 482044966076-sa80ajv8s0i3lbulakk5uev5mefhiled.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1186357288641276
            client-secret: bf350f64edbeb580939e6ef7d3eb4b85
            scope:
              - email
              - public_profile
          naver:
            client-id: jo6jVfje8daqvslF5fVn
            client-secret: tL88ujwkZO
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
